### PR TITLE
refactor(frontend): update image tags [WIT-87]

### PR DESCRIPTION
**Pull request by Darianlmj**
- Updated image tags to use `next/image` instead of `next/legacy/images`.
- All images will have the attribute `loading="lazy"` by default unless specified otherwise.

### CODE REVIEW

**Comment by lhjt** [comment]
Can't merge this yet because of deployment environment configuration (I am investigating):
image

**Comment by Darianlmj** [comment]
Yup, I guess this PR will be blocked until the deployment stuff gets resolved

**Review by gracexkan — APPROVED** [review]
lgtm!

**Comment by gracexkan** [comment]
> Can't merge this yet because of deployment environment configuration (I am investigating): image

Yeah it won't be deployed but it should be fine to merge it into jh/fix as that isn't being used for deployment yet

**Pull request merged**
